### ISSUE TITLE
Unable to run the test

### ISSUE THREAD

**Issue by andriyrizhiy** [mingcv/DSRNet#1]
I tried to run test, with command 
`python test_sirs.py --inet ytmt_ucs_old --model twostage_ytmt_model --name ytmt_uct_sirs_test --hyper --if_align --resume --icnn_path ./checkpoints/ytmt_uct_sirs/ytmt_uct_sirs_68_077_00595364.pt`

but have an error:
`-------------- End ----------------
Traceback (most recent call last):
  File "test_sirs.py", line 25, in <module>
    engine = Engine(opt)
  File "/home/andrew/reseach_cloned/DSRNet/engine.py", line 19, in __init__
    self.__setup()
  File "/home/andrew/reseach_cloned/DSRNet/engine.py", line 28, in __setup
    self.model = make_model(self.opt.model)()  # models.__dict__[self.opt.model]()
  File "/home/andrew/reseach_cloned/DSRNet/models/__init__.py", line 8, in make_model
    base = importlib.import_module('models.' + name)
  File "/root/miniconda3/envs/skylumml/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'models.twostage_ytmt_model'`

**Comment by mingcv** [comment]
Hi~ We have updated the evaluation code. Please see README.md for more instructions. We have released the small version of the DSRNet, and more checkpoints will be released later, because we have reorganized the network structure and it takes time to retrain them.

**Comment by andriyrizhiy** [comment]
thank you, now it works! but I ran test_sirs.py with modifications on 126-134 lines in file dsrnet_model_sirs.py
` with torch.no_grad():
            # print(self.forward())
            self.forward()
            output_i = tensor2im(self.output_t)
            output_j = tensor2im(self.output_r)
            if self.data_name is not None and savedir is not None:
                Image.fromarray(output_i.astype(np.uint8)).save(join(savedir, name, '{}_l.png'.format(self.opt.name)))
                Image.fromarray(output_j.astype(np.uint8)).save(join(savedir, name, '{}_r.png'.format(self.opt.name)))
                Image.fromarray(tensor2im(self.input).astype(np.uint8)).save(join(savedir, name, 'm_input.png'))
`

**Comment by andriyrizhiy** [comment]
and when you are planning to release biiger models?

**Comment by mingcv** [comment]
> thank you, now it works! but I ran test_sirs.py with modifications on 126-134 lines in file dsrnet_model_sirs.py `with torch.no_grad(): # print(self.forward()) self.forward() output_i = tensor2im(self.output_t) output_j = tensor2im(self.output_r) if self.data_name is not None and savedir is not None: Image.fromarray(output_i.astype(np.uint8)).save(join(savedir, name, '{}_l.png'.format(self.opt.name))) Image.fromarray(output_j.astype(np.uint8)).save(join(savedir, name, '{}_r.png'.format(self.opt.name))) Image.fromarray(tensor2im(self.input).astype(np.uint8)).save(join(savedir, name, 'm_input.png'))`

Thanks for your bug report, and it has been fixed.

We will release the other checkpoints as soon as possible (no longer than a week). If you are eager to see them, I can share you with the results of them or the unorganized code.

**Comment by andriyrizhiy** [comment]
thanks, I will wait your release version!

**Comment by mingcv** [comment]
> thanks, I will wait your release version!

Hi~ We have released the large version of the DSRNet. Please check the README.md for more details

**Comment by andriyrizhiy** [comment]
thank you
