### ISSUE TITLE
Missing keys in state_dict 

### ISSUE THREAD

**Issue by nivedwho** [mingcv/DSRNet#12]
Getting model loading error while to load my training checkpoints while running 'test_sirs.py' with 
```weight_path='checkpoints/dsrnet_l/weights/20240831-120945/dsrnet_l_latest.pt'```

Full error log - 

```
RuntimeError: Error(s) in loading state_dict for DSRNet:
        Missing key(s) in state_dict: "intro.block5.0.a_l", "intro.block5.0.a_r", "intro.block5.0.b", "intro.block5.0.block1.0.seq.0.weight", "intro.block5.0.block1.0.seq.0.bias", "intro.block5.0.block1.0.seq.1.weight", "intro.block5.0.block1.0.seq.1.bias", "intro.block5.0.block1.0.seq.2.weight", "intro.block5.0.block1.0.seq.2.bias", "intro.block5.0.block1.2.seq.0.ca.1.weight", "intro.block5.0.block1.2.seq.0.ca.1.bias", "intro.block5.0.block1.3.seq.0.weight", "intro.block5.0.block1.3.seq.0.bias", "intro.block5.0.block2.0.seq.0.weight", "intro.block5.0.block2.0.seq.0.bias", "intro.block5.0.block2.0.seq.1.weight", "intro.block5.0.block2.0.seq.1.bias", "intro.block5.0.block2.2.seq.0.weight", "intro.block5.0.block2.2.seq.0.bias.....
        Unexpected key(s) in state_dict: "weight", "epoch", "iterations", "opt_g". 
```
Also my dsrnet_l_latest.pt is 1.4gb. 

How to run the test script with the training checkpoint?

**Comment by mingcv** [comment]
Hi~ you need to load the checkpoint with the "weight" key to index your checkpoint dict by modifying 
https://github.com/mingcv/DSRNet/blob/029d495f8ec7e0be5b97215f0f113c4e599645f5/models/dsrnet_model_sirs.py#L247
into 
` state_dict = torch.load(weight_path) ['weight']`

**Comment by mingcv** [comment]
I added an if condition to check if extra information is saved together with the network weight. Now the model can load state_dict adaptively.

https://github.com/mingcv/DSRNet/blob/7953e4045f89dd0b76d63bd3ac3eb4946f5cabc6/models/dsrnet_model_sirs.py#L245-L260
