### ISSUE TITLE
Is residue layer considered together as the reflective layer?

### ISSUE THREAD

**Issue by yghirofumi** [mingcv/DSRNet#16]
Thank you for your excellent research. I am not sure how to interpret the residue layer.
Can I interpret the residue layer as a reflective layer that did not follow the linear assumption and is included in the broadly defined reflective layer?

**Comment by mingcv** [comment]
Thank you for your thoughtful question. In our paper, we consider the residue layer as a third component distinct from both the reflective and transmissive layers. Visually, it can be seen as the coupling between the reflective and transmissive layers. When this residue layer is assigned to either of the two components, it causes a deviation from the ideal ground truth for both.

**Comment by yghirofumi** [comment]
Thank you for your answer. I will consider the importance of the linear assumption a bit more.
