### ISSUE TITLE
The weight seems incorrect

### ISSUE THREAD

**Issue by CrushDemo01** [mingcv/DSRNet#2]
Hello, I'm trying the weights you provided, but they don't seem to meet the metrics in the paper.

**Comment by mingcv** [comment]
I reimplemented the network architecture in the open repository. Please refer to [the provided table in this repository](https://github.com/mingcv/DSRNet?tab=readme-ov-file#trained-weights).

**Comment by mingcv** [comment]
Since there are no further questions, we'll go ahead and close this issue for now. If you have additional questions in the future, feel free to open a new issue.
