### ISSUE TITLE
About training set

### ISSUE THREAD

**Issue by Badwoman-xuan** [mingcv/DSRNet#4]
Does the released weights here include the nature200 dataset as part of the training set, or were they trained solely on synthesis data and real90?

**Comment by mingcv** [comment]
No, the currently released models do not include the nature200 in their training phase. We've noticed this point brings some misunderstanding recently, and we will release a version with a full data setting soon.

**Comment by mingcv** [comment]
Hi, we've released the full training setting with nature200 dataset of the DSRNet, as well as the quantitative results and checkpoint of the new model (with "4000" notation). Please check it out. :)
