### ISSUE TITLE
test_sirs.py problem when i test my own data ,after precessing to save the processed image got this wrong

### ISSUE THREAD

**Issue by lofangmeng** [mingcv/DSRNet#5]
File ~/Downloads/DSRNet-main/models/dsrnet_model_sirs.py:143 in test
    Image.fromarray(tensor2im(torch.clip((output_rr + 1) / 2, 0., 1.)).astype(np.uint8)).save(

TypeError: clip() received an invalid combination of arguments - got (numpy.ndarray, float, float), but expected one of:
 * (Tensor input, Number min, Number max, *, Tensor out)
 * (Tensor input, Tensor min, Tensor max, *, Tensor out)

**Comment by mingcv** [comment]
Thanks for reporting it, and it's fixed now.
