### ISSUE TITLE
About Custom Dataset

### ISSUE THREAD

**Issue by DrawingProcess** [mingcv/DSRNet#6]
Is it possible to make a custom dataset and reflection remodel? 
If possible, should I do an inference after training separately?

**Comment by mingcv** [comment]
Of course, you can make a custom dataset and customize your superimposition process by modifying the following lines: 
https://github.com/mingcv/DSRNet/blob/27d0e050a129a217503a673d8a7baf5b1d482a79/data/sirs_dataset.py#L83-L118

It is not necessary to do an inference after training the model. You can directly deploy it in your application scenario after training.

**Comment by mingcv** [comment]
Since there are no further questions, we'll go ahead and close this issue for now. If you have additional questions in the future, feel free to open a new issue.
