### ISSUE TITLE
Used for custom data

### ISSUE THREAD

**Issue by kiddoray** [mingcv/DSRNet#8]
I want to remove the reflections on my own data for further use. How should I preprocess my data and place it? Thx

**Comment by mingcv** [comment]
Will you train the model on your own data or just for testing?

**Comment by kiddoray** [comment]
> Will you train the model on your own data or just for testing?

i wanna use the model just for testing, thx

**Comment by mingcv** [comment]
Hi, I've updated the code of test_sirs.py and the README.md. Please check the new guidance to test our model on your own images.

**Comment by mingcv** [comment]
Since there are no further questions, we'll go ahead and close this issue for now. If you have additional questions in the future, feel free to open a new issue.
