### ISSUE TITLE
Missing keys in state_dict

### ISSUE THREAD

**Issue by kiddoray** [mingcv/DSRNet#9]
I am trying to test on my own images with the following code: 
`python test_sirs.py --inet dsrnet_l --model dsrnet_model_sirs --dataset sirs_dataset  --name dsrnet_l_4000_test --hyper --if_align --resume --weight_path "./weights/dsrnet_s_epoch14.pt" --base_dir "my data path"`
And i load the model with the weights you provided but got this error:

Missing key(s) in state_dict: "lrm.blocks_merge.2.a", "lrm.blocks_merge.2.b", "lrm.blocks_merge.2.block1.0.weight", "lrm.blocks_merge.2.block1.0.bias", "lrm.blocks_merge.2.block1.1.weight", "lrm.blocks_merge.2.block1.1.bias", "lrm.blocks_merge.2.block1.2.weight", "lrm.blocks_merge.2.block1.2.bias", "lrm.blocks_merge.2.block1.4.ca.1.weight", "lrm.blocks_merge.2.block1.4.ca.1.bias", "lrm.blocks_merge.2.block1.5.weight", "lrm.blocks_merge.2.block1.5.bias", "lrm.blocks_merge.2.block2.0.weight", "lrm.blocks_merge.2.block2.0.bias", "lrm.blocks_merge.2.block2.1.weight", "lrm.blocks_merge.2.block2.1.bias", "lrm.blocks_merge.2.block2.3.weight", "lrm.blocks_merge.2.block2.3.bias", "lrm.blocks_merge.3.a", "lrm.blocks_merge.3.b", "lrm.blocks_merge.3.block1.0.weight", "lrm.blocks_merge.3.block1.0.bias", "lrm.blocks_merge.3.block1.1.weight", "lrm.blocks_merge.3.block1.1.bias", "lrm.blocks_merge.3.block1.2.weight", "lrm.blocks_merge.3.block1.2.bias", "lrm.blocks_merge.3.block1.4.ca.1.weight", "lrm.blocks_merge.3.block1.4.ca.1.bias", "lrm.blocks_merge.3.block1.5.weight", "lrm.blocks_merge.3.block1.5.bias", "lrm.blocks_merge.3.block2.0.weight", "lrm.blocks_merge.3.block2.0.bias", "lrm.blocks_merge.3.block2.1.weight", "lrm.blocks_merge.3.block2.1.bias", "lrm.blocks_merge.3.block2.3.weight", "lrm.blocks_merge.3.block2.3.bias".

**Comment by mingcv** [comment]
This problem should be fixed by the new update. Please check it.

**Comment by mingcv** [comment]
Since there are no further questions, we'll go ahead and close this issue for now. If you have additional questions in the future, feel free to open a new issue.
